host: <%= host = "http://www.iana.org/domains/example" %>
another_host: <%= another_host = "http://www.anotherhost.com" %>
type_host: <%= type_host = "http://types.lelylan.com" %>
unite_node_nost: <%= unite_node_host = "http://nodes.lelylan.com" %>
user: 
  uri: <%= "#{host}/users/alice" %>
  email: 'alice@example.com'
  password: 'example'
another_user: 
  uri: <%= "#{host}/users/bob" %>
  email: 'bob@example.com'
type:
  uri: <%= type_uri = "#{type_host}/types/dimmer" %>
  name: 'Dimmer'
device:
  uri: <%= device_uri = "#{host}/devices/closet_dimmer" %>
  name: 'Closet dimmer'
another_device:
  uri: <%= "#{host}/devices/not_owned_closet_dimmer" %>
  name: 'Not owned closet dimmer'
properties:
  status:
    uri: <%= status_uri = "#{type_host}/properties/status" %> 
    name: 'Status'
    default_value: 'on'
  intensity:
    uri: <%= intensity_uri = "#{type_host}/properties/intensity" %> 
    name: 'Intensity'
    default_value: '0.0'
functions:
  set_intensity:
    id: <%= set_intensity_id = "set_intensity" %>
    uri: <%= set_intensity_function_uri = "#{type_host}/functions/#{set_intensity_id}" %>
    name: "Set intensity"
  turn_on:
    id: <%= turn_on_id = "turn_on" %>
    uri: <%= turn_on_function_uri = "#{type_host}/functions/#{turn_on_id}" %>
    name: "Turn on"
  turn_off:
    id: <%= turn_off_id = "turn_off" %>
    uri: <%= turn_off_function_uri = "#{type_host}/functions/#{turn_off_id}" %>
    name: "Turn off"
pending:
  uri: <%= "#{host}/pendings/set_intensity" %>
pending_closed:
  uri: <%= "#{host}/pendings/closed_set_intensity" %>
unite_node:
  uri: <%= unite_node_uri = "#{unite_node_host}/nodes/home_gateway" %>
  physical_id: '<%= physical_id = "0x3a91fb2e" %>'
history:
  uri: <%= "#{host}/histories/set_intensity" %>
validation: 
  valid_uri: 'http://example.com'
  not_valid_uri: 'example'
messages:
  access_denied: 'Access denied'
type_json: |
  {
    "id": "<%= type_json_id = "4dc24833d033a9778500000a" %>",
    "uri": "<%= type_uri %>",
    "name": "Dimmer",
    "created_at": "2011-05-05 08:48:19 +0200",
    "updated_at": "2011-05-05 08:48:19 +0200",
    "properties": [
        {
            "id": "4db94c2fd033a917e7000001",
            "uri": "<%= intensity_uri %>",
            "name": "Intensity",
            "default": "0.0",
            "values": [
                "0.0",
                "2.0",
                "4.0",
                "6.0",
                "8.0",
                "10.0" 
            ],
            "created_at": "2011-04-28 13:14:55 +0200",
            "updated_at": "2011-05-05 08:32:20 +0200" 
        },
        {
            "id": "4dc2441ad033a97785000001",
            "uri": "<%= status_uri %>",
            "name": "Status",
            "default": "off",
            "values": [
                "on",
                "off" 
            ],
            "created_at": "2011-05-05 08:30:50 +0200",
            "updated_at": "2011-05-05 08:30:50 +0200" 
        } 
    ],
    "functions": [
        {
            "id": "4dc24514d033a97785000002",
            "uri": "<%= turn_on_function_uri %>",
            "name": "Turn on",
            "created_at": "2011-05-05 08:35:00 +0200",
            "updated_at": "2011-05-05 08:43:59 +0200",
            "properties": [
                {
                    "uri": "http://localhost:3000/properties/4dc2441ad033a97785000001",
                    "values": [
                        "on" 
                    ],
                    "secret": "false",
                    "before": "false",
                    "created_at": "",
                    "updated_at": "" 
                } 
            ] 
        },
        {
            "id": "4dc24522d033a97785000003",
            "uri": "<%= turn_off_function_uri %>",
            "name": "Turn off",
            "created_at": "2011-05-05 08:35:14 +0200",
            "updated_at": "2011-05-05 08:45:04 +0200",
            "properties": [
                {
                    "uri": "http://localhost:3000/properties/4dc2441ad033a97785000001",
                    "values": [
                        "off" 
                    ],
                    "secret": "false",
                    "before": "false",
                    "created_at": "",
                    "updated_at": "" 
                } 
            ] 
        },
        {
            "id": "4dc24532d033a97785000004",
            "uri": "<%= set_intensity_function_uri %>",
            "name": "Set intensity",
            "created_at": "2011-05-05 08:35:30 +0200",
            "updated_at": "2011-05-05 08:45:57 +0200",
            "properties": [
                {
                    "uri": "http://localhost:3000/properties/4db94c2fd033a917e7000001",
                    "values": "",
                    "secret": "false",
                    "before": "false",
                    "created_at": "",
                    "updated_at": "" 
                } 
            ] 
        } 
    ],
    "statuses": [
        {
            "uri": "http://localhost:3000/statuses/4dc24833d033a9778500000b",
            "created_at": "",
            "updated_at": "" 
        } 
    ]
  }
function_json: |
  {
      "id": "4dc24532d033a97785000004",
      "uri": "<%=set_intensity_function_uri%>",
      "name": "Set intensity",
      "created_at": "2011-05-05 08:35:30 +0200",
      "updated_at": "2011-05-05 08:45:57 +0200",
      "properties": [
          {
              "uri": "<%= intensity_uri %>",
              "value": "",
              "secret": "false",
              "before": "false",
              "created_at": "",
              "updated_at": "" 
          },
          {
              "uri": "<%= status_uri %>",
              "value": "on",
              "secret": "false",
              "before": "false",
              "created_at": "",
              "updated_at": "" 
          } 
      ] 
  } 
unite_node_json: |
  {
      "physical_id": "<%= physical_id %>",
      "unite_node_uri": "<%= unite_node_uri %>",
      "properties": [
          {
              "uri": "<%= intensity_uri %>",
              "value": "10.0"
          },
          {
              "uri": "<%= status_uri %>",
              "value": "off"
          } 
      ] 
  } 

